[package]
name = "sample-cli"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "sample-cli"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5", features = ["derive"] }

[dev-dependencies]
testscript-rs = { path = "../.." }